import math
from theia.terrain import elevationAt
from theia.distance import burstvincentydistance, haversine, R_EARTH, linspace
from theia.types import Point


# Generated by ChatGPT.
def has_line_of_sight(start: Point, stop: Point, step_m: float) -> bool:
    """
    Checks line of sight between two points accounting for Earth curvature
    and terrain elevation.

    step_m controls sampling resolution along the path.
    """

    def rad(p):
        return math.radians(p.lat), math.radians(p.lon)

    lat1, lon1 = rad(start)
    lat2, lon2 = rad(stop)

    distance = haversine(start.lon, start.lat, stop.lon, stop.lat)

    if distance == 0:
        return True

    steps = max(1, int(distance / step_m) + 1)

    # Heights above Earth's center
    h1 = R_EARTH + start.alt
    h2 = R_EARTH + stop.alt

    for i in range(1, steps):
        t = i / steps

        # Interpolate along great circle
        A = math.sin((1 - t) * distance / R_EARTH) / math.sin(distance / R_EARTH)
        B = math.sin(t * distance / R_EARTH) / math.sin(distance / R_EARTH)

        x = A * math.cos(lat1) * math.cos(lon1) + B * math.cos(lat2) * math.cos(lon2)
        y = A * math.cos(lat1) * math.sin(lon1) + B * math.cos(lat2) * math.sin(lon2)
        z = A * math.sin(lat1) + B * math.sin(lat2)

        lat = math.atan2(z, math.sqrt(x * x + y * y))
        lon = math.atan2(y, x)

        lat_deg = math.degrees(lat)
        lon_deg = math.degrees(lon)

        # Terrain height above Earth's center
        terrain = R_EARTH + elevationAt(lat_deg, lon_deg)

        # Height of LOS ray at this point
        ray_height = (1 - t) * h1 + t * h2

        if terrain > ray_height:
            return False

    return True


def line_of_sight_along_ray(
    emitter_pos: Point,
    target_bearing: float,
    target_alt: float,
    d_max: float,
    dist_res: float,
) -> Point:
    # March from the point at distance max_dist in direction theta
    # towards the emitter.
    # As long as there is no line of sight: Keep marching.
    # If there is a LoS, return the point.
    furthest = burstvincentydistance(
        (emitter_pos.lat, emitter_pos.lon), d_max, target_bearing
    )
    furthest = Point(lat=furthest[0], lon=furthest[1], alt=target_alt)
    for point in linspace(furthest, emitter_pos, dist_res):
        point.alt = target_alt
        if has_line_of_sight(emitter_pos, point, dist_res):
            return point
    return emitter_pos
