import math
from scipy.optimize import bisect
from theia.terrain import elevationAt
from theia.distance import burstvincentydistance, haversine, R_EARTH, linspace
from theia.types import Point


# Generated by ChatGPT.
def has_line_of_sight(start: Point, stop: Point, step_m: float) -> bool:
    """
    Checks line of sight between two points accounting for Earth curvature
    and terrain elevation.

    step_m controls sampling resolution along the path.
    """

    def rad(p):
        return math.radians(p.lat), math.radians(p.lon)

    lat1, lon1 = rad(start)
    lat2, lon2 = rad(stop)

    distance = haversine(start.lon, start.lat, stop.lon, stop.lat)

    if distance == 0:
        return True

    steps = max(1, int(distance / step_m) + 1)

    # Heights above Earth's center
    h1 = R_EARTH + start.alt
    h2 = R_EARTH + stop.alt

    for i in range(1, steps):
        t = i / steps

        # Interpolate along great circle
        A = math.sin((1 - t) * distance / R_EARTH) / math.sin(distance / R_EARTH)
        B = math.sin(t * distance / R_EARTH) / math.sin(distance / R_EARTH)

        x = A * math.cos(lat1) * math.cos(lon1) + B * math.cos(lat2) * math.cos(lon2)
        y = A * math.cos(lat1) * math.sin(lon1) + B * math.cos(lat2) * math.sin(lon2)
        z = A * math.sin(lat1) + B * math.sin(lat2)

        lat = math.atan2(z, math.sqrt(x * x + y * y))
        lon = math.atan2(y, x)

        lat_deg = math.degrees(lat)
        lon_deg = math.degrees(lon)

        # Terrain height above Earth's center
        terrain = R_EARTH + elevationAt(lat_deg, lon_deg)

        # Height of LOS ray at this point
        ray_height = (1 - t) * h1 + t * h2

        if terrain > ray_height:
            return False

    return True


def line_of_sight_along_ray(
    emitter_pos: Point,
    target_bearing: float,
    target_alt: float,
    d_max: float,
    dist_res: float,
) -> Point:
    def loss(distance: float) -> float:
        p = burstvincentydistance(
            (emitter_pos.lat, emitter_pos.lon),
            distance,
            target_bearing,
            target_alt,
        )
        if has_line_of_sight(emitter_pos, p, dist_res):
            return 1.0
        else:
            return -1.0

    # We need to catch this special case (line of sight at maximum range)
    # because scipy.optimize.bisect expects the extreme values to have different
    # values.
    if loss(d_max) > 0:
        return burstvincentydistance(
            (emitter_pos.lat, emitter_pos.lon),
            d_max,
            target_bearing,
            target_alt,
        )

    d = bisect(loss, 0, d_max, xtol=dist_res)
    return burstvincentydistance(
        (emitter_pos.lat, emitter_pos.lon),
        d,
        target_bearing,
        target_alt,
    )
